"""empty message

Revision ID: 3ba403cc65f0
Revises: 5eaa9637089c
Create Date: 2025-02-21 17:50:13.165374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba403cc65f0'
down_revision = '5eaa9637089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros_create', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))
        batch_op.drop_column('Link')
        batch_op.drop_column('Ano')
        batch_op.drop_column('Título')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros_create', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Título', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Ano', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Link', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('link')
        batch_op.drop_column('ano')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
