"""altera link para string

Revision ID: 5eaa9637089c
Revises: eb1e5e0a8b97
Create Date: 2025-02-21 17:28:28.097392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eaa9637089c'
down_revision = 'eb1e5e0a8b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros_create', schema=None) as batch_op:
        batch_op.alter_column('Link',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros_create', schema=None) as batch_op:
        batch_op.alter_column('Link',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
