"""livros_create

Revision ID: eb1e5e0a8b97
Revises: ea5b1b9cf2a5
Create Date: 2025-02-19 15:38:48.215068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1e5e0a8b97'
down_revision = 'ea5b1b9cf2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros_create',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Título', sa.String(length=100), nullable=True),
    sa.Column('Ano', sa.String(length=100), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('Link', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_create')
    # ### end Alembic commands ###
